"""
Fallback mock prescription returned when the Gemini API quota is exhausted.
Mirrors the Prescription Pydantic schema exactly.
"""

MOCK_PRESCRIPTION = {
    "_demo_mode": True,
    "prescription_id": "RX-2022-1012-001",
    "date_issued": "2022-10-12T00:00:00Z",
    "patient": {
        "name": "Sachin Sansare",
        "date_of_birth": "1994-01-01",
        "age": 28,
        "gender": "Male",
        "blood_group": None,
        "contact_number": None,
        "emergency_contact": None,
        "known_allergies": [],
        "chronic_conditions": [],
    },
    "doctor": {
        "practitioner_id": None,
        "name": "Dr. Amita",
        "specialization": "General Dentistry",
        "license_number": None,
        "qualifications": None,
        "clinic_name": "THE White TUSK",
        "clinic_address": "Contact: +91 8108112511, info@thewhitetusk.com",
        "contact_number": "+91 8108112511",
    },
    "medications": [
        {
            "name": "Augmentin",
            "strength": "625mg",
            "dosage": "1 tablet",
            "frequency": "Twice a day (morning and night)",
            "route": "Oral",
            "duration": "5 days",
            "purpose": "To fight the bacterial infection in your mouth and gums, and to prevent it from spreading after your dental procedure.",
            "price_inr": "₹240–280 / strip of 6 tablets",
            "instructions": "Take after meals",
            "side_effects": ["Nausea", "Vomiting", "Diarrhea", "Abdominal pain", "Skin rash", "Candidiasis"],
            "contraindications": [
                "Hypersensitivity to penicillin or clavulanic acid",
                "History of cholestatic jaundice associated with amoxicillin-clavulanate",
            ],
            "precautions": "Use with caution in patients with renal or hepatic impairment.",
            "alternatives": [
                {"name": "Moxikind-CV 625mg",              "type": "alternative", "price_inr": "₹160–185 / strip of 6 tablets"},
                {"name": "Clavam 625mg",                   "type": "alternative", "price_inr": "₹195–225 / strip of 6 tablets"},
                {"name": "Amoxyclav 625mg",                "type": "alternative", "price_inr": "₹170–200 / strip of 6 tablets"},
                {"name": "Amoxicillin + Clavulanic Acid 625mg", "type": "generic", "price_inr": "₹80–120 / strip of 6 tablets"},
            ],
        },
        {
            "name": "Enzoflam",
            "strength": "Diclofenac 50mg + Paracetamol 325mg + Serratiopeptidase 15mg",
            "dosage": "1 tablet",
            "frequency": "Twice a day (morning and night)",
            "route": "Oral",
            "duration": "5 days",
            "purpose": "To relieve pain, reduce swelling, and bring down inflammation in your gums and jaw after the dental procedure.",
            "price_inr": "₹120–150 / strip of 10 tablets",
            "instructions": "Take after meals",
            "side_effects": ["Nausea", "Stomach pain", "Indigestion", "Dizziness", "Drowsiness"],
            "contraindications": [
                "Hypersensitivity to NSAIDs",
                "Active peptic ulcer",
                "Severe renal or hepatic impairment",
                "Third trimester of pregnancy",
            ],
            "precautions": "Avoid alcohol. Use with caution in cardiovascular disease or hypertension.",
            "alternatives": [
                {"name": "Serata-D Tablet",                         "type": "alternative", "price_inr": "₹90–115 / strip of 10 tablets"},
                {"name": "Enzoflam-D Tablet",                       "type": "alternative", "price_inr": "₹105–135 / strip of 10 tablets"},
                {"name": "Diclofenac + Paracetamol + Serratiopeptidase", "type": "generic", "price_inr": "₹40–65 / strip of 10 tablets"},
            ],
        },
        {
            "name": "Pan D",
            "strength": "Pantoprazole 40mg + Domperidone 10mg",
            "dosage": "1 tablet",
            "frequency": "Once a day (morning)",
            "route": "Oral",
            "duration": "5 days",
            "purpose": "To protect your stomach — it reduces acid and prevents the nausea or stomach upset that the other medicines (antibiotic and painkiller) can cause.",
            "price_inr": "₹130–160 / strip of 10 tablets",
            "instructions": "Take before meals",
            "side_effects": ["Headache", "Nausea", "Diarrhea", "Dizziness"],
            "contraindications": [
                "Hypersensitivity to pantoprazole or domperidone",
                "Moderate to severe hepatic impairment",
            ],
            "precautions": "Long-term use may increase risk of osteoporosis.",
            "alternatives": [
                {"name": "Pantocid-D",              "type": "alternative", "price_inr": "₹95–120 / strip of 10 tablets"},
                {"name": "Pentaloc-D",              "type": "alternative", "price_inr": "₹105–130 / strip of 10 tablets"},
                {"name": "Pantoprazole + Domperidone", "type": "generic", "price_inr": "₹30–55 / strip of 10 tablets"},
            ],
        },
        {
            "name": "Hexigel Gum Paint",
            "strength": "0.2% Chlorhexidine Gluconate",
            "dosage": "Apply a small amount and massage",
            "frequency": "Twice a day (morning and night)",
            "route": "Topical (oral)",
            "duration": "1 week",
            "purpose": "To keep your gums clean, kill bacteria, and prevent gum infection at the site of your dental treatment.",
            "price_inr": "₹90–120 / 30g tube",
            "instructions": "Massage onto gums. Do not swallow.",
            "side_effects": ["Temporary staining of teeth", "Altered taste", "Burning sensation"],
            "contraindications": ["Hypersensitivity to chlorhexidine"],
            "precautions": "For oral use only. Do not swallow. Keep out of reach of children.",
            "alternatives": [
                {"name": "Rexidin M Forte Gel",        "type": "alternative", "price_inr": "₹70–90 / 30g tube"},
                {"name": "Perio-Aid Gel",               "type": "alternative", "price_inr": "₹60–80 / tube"},
                {"name": "Chlorhexidine Gluconate Gel", "type": "generic",     "price_inr": "₹35–55 / tube"},
            ],
        },
    ],
    "chief_complaint": None,
    "diagnosis": [],
    "vitals_at_visit": None,
    "clinical_notes": None,
    "follow_up_date": None,
}
